import { useEffect, useState } from 'react';
import { Database, Globe2, HardDrive, Languages, LockKeyhole, MonitorCog, Moon, ShieldCheck, Wifi, WifiOff } from 'lucide-react';
import { getHealth } from '../../app/api';
import type { AppLanguage } from '../../app/types';
export default function SettingsPage({ lang }: { lang: AppLanguage }) {
  const ar = lang === 'ar';
  const [health, setHealth] = useState<{ status: string; database: string; integration_mode: string } | null>(null);
  useEffect(() => { getHealth().then(setHealth).catch(() => setHealth(null)); }, []);
  return <section className="settings-page"><div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-star">✦</span>{ar ? 'مركز الإدارة' : 'ADMINISTRATION'}</div><h1>{ar ? 'إعدادات النظام' : 'System settings'}<span className="heading-period">.</span></h1><p>{ar ? 'تحكم في بيئة العمل المحلية وتهيئة النظام.' : 'Manage your local workspace and system configuration.'}</p></div></div>
  <div className="settings-grid"><article className="panel setting-panel"><div className="panel-heading"><div><span className="eyebrow">{ar ? 'بيئة التشغيل' : 'RUNTIME'}</span><h2>{ar ? 'الخدمات المحلية' : 'Local services'}</h2></div><MonitorCog size={18}/></div><SettingRow icon={Database} label={ar ? 'قاعدة البيانات' : 'Database'} value={health?.database ?? (ar ? 'غير متاحة — شغّل API' : 'Unavailable — start API')} ok={health?.database === 'connected'}/><SettingRow icon={Wifi} label={ar ? 'واجهة API' : 'API service'} value={health?.status === 'ok' ? '127.0.0.1:8000' : (ar ? 'غير متصلة' : 'Disconnected')} ok={health?.status === 'ok'}/><SettingRow icon={Globe2} label={ar ? 'وضع التكامل' : 'Integration mode'} value={health?.integration_mode ?? 'offline-first'} ok/></article><article className="panel setting-panel"><div className="panel-heading"><div><span className="eyebrow">{ar ? 'الحماية والخصوصية' : 'SECURITY & PRIVACY'}</span><h2>{ar ? 'بياناتك على جهازك' : 'Your data stays local'}</h2></div><LockKeyhole size={18}/></div><div className="privacy-card"><span className="privacy-icon"><ShieldCheck size={20}/></span><b>{ar ? 'لا توجد قاعدة بيانات سحابية' : 'No cloud database'}</b><p>{ar ? 'يعمل SHOPNEX محليًا. يتصل بالإنترنت فقط عند استخدام تكامل خارجي كزاتكا.' : 'SHOPNEX operates locally. Internet is used only when you invoke an external integration such as ZATCA.'}</p></div><SettingRow icon={HardDrive} label={ar ? 'النسخ الاحتياطي' : 'Backups'} value={ar ? 'إعداد محلي — قيد الإعداد' : 'Local setup — in progress'}/><SettingRow icon={LockKeyhole} label={ar ? 'خزنة الأسرار' : 'Credential vault'} value={ar ? 'مخزن نظام التشغيل' : 'OS key store'}/></article><article className="panel setting-panel appearance-panel"><div className="panel-heading"><div><span className="eyebrow">{ar ? 'تفضيلات العرض' : 'DISPLAY PREFERENCES'}</span><h2>{ar ? 'المظهر واللغة' : 'Appearance & language'}</h2></div><MonitorCog size={18}/></div><SettingRow icon={Moon} label={ar ? 'المظهر الافتراضي' : 'Default theme'} value={ar ? 'داكن فضائي' : 'Cosmic dark'}/><SettingRow icon={Languages} label={ar ? 'اللغة الافتراضية' : 'Default language'} value={ar ? 'العربية (RTL)' : 'Arabic (RTL)'}/><div className="setting-footnote"><WifiOff size={14}/>{ar ? 'تفضيلات العرض التفاعلية متاحة من الشريط العلوي.' : 'Interactive display preferences are available in the top bar.'}</div></article></div></section>;
}
function SettingRow({ icon: Icon, label, value, ok }: { icon: typeof Database; label: string; value: string; ok?: boolean }) { return <div className="setting-row"><span className="setting-row-icon"><Icon size={15}/></span><span>{label}</span><b className={ok ? 'setting-ok' : ''}>{ok && <i/>}{value}</b></div>; }
