import { useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpLeft, Boxes, CircleAlert, Package, Plus, Search, SlidersHorizontal, Warehouse } from 'lucide-react';
import type { AppLanguage } from '../../app/types';

const products = [
  { sku: 'SHX-1042', name: 'سماعة لاسلكية — Nova Pro', category: 'إلكترونيات', qty: 24, price: '449.00', location: 'مستودع الرياض', flag: 'متوفر' },
  { sku: 'SHX-2031', name: 'مصباح مكتبي — Arc Lite', category: 'المنزل والمكتب', qty: 7, price: '189.00', location: 'مستودع جدة', flag: 'منخفض' },
  { sku: 'SHX-1107', name: 'شاحن سريع — Pulse 65W', category: 'إلكترونيات', qty: 52, price: '129.00', location: 'مستودع الرياض', flag: 'متوفر' },
  { sku: 'SHX-4401', name: 'حامل شاشة — Orbit Desk', category: 'المنزل والمكتب', qty: 3, price: '325.00', location: 'مستودع الخبر', flag: 'منخفض' },
  { sku: 'SHX-3180', name: 'لوحة مفاتيح — Comet 75', category: 'إلكترونيات', qty: 18, price: '379.00', location: 'مستودع الدمام', flag: 'متوفر' },
  { sku: 'SHX-5224', name: 'زجاجة حرارية — Terra', category: 'نمط الحياة', qty: 0, price: '89.00', location: 'مستودع الرياض', flag: 'نفد' },
];
export default function InventoryPage({ lang, productsOnly = false }: { lang: AppLanguage; productsOnly?: boolean }) {
  const ar = lang === 'ar';
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [message, setMessage] = useState(false);
  const visible = useMemo(() => products.filter((p) => `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'low' && p.flag !== 'متوفر') || (filter === 'available' && p.flag === 'متوفر'))), [query, filter]);
  return <section className="inventory-page"><div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-star">✦</span>{ar ? 'مساحة العمل · المخزون' : 'WORKSPACE · INVENTORY'}</div><h1>{productsOnly ? (ar ? 'المنتجات والتصنيفات' : 'Products & categories') : (ar ? 'المخزون والمستودعات' : 'Inventory & warehouses')}<span className="heading-period">.</span></h1><p>{ar ? 'تابع حركة الأصناف ومستويات التوفر عبر الفروع.' : 'Track item movement and availability across branches.'}</p></div><div className="heading-actions"><span className="demo-pill"><i/>{ar ? 'بيانات تجريبية' : 'DEMO DATA'}</span><button className="button button-primary" onClick={() => setMessage(true)}><Plus size={15}/>{ar ? 'إضافة صنف' : 'Add product'}</button></div></div>
  {message && <div className="inline-alert warning"><span><CircleAlert size={16}/></span>{ar ? 'واجهة إضافة الصنف ستُفعّل مع توصيل API المحلي — لا تُحفظ بيانات هذا العرض.' : 'Product creation will activate with the local API. This demo screen does not persist changes.'}<button className="icon-button" onClick={() => setMessage(false)}><ArrowDownLeft size={15}/></button></div>}
  <div className="operations-summary inventory-summary"><div className="panel ops-summary-card"><span className="metric-icon teal"><Package size={17}/></span><span className="eyebrow">{ar ? 'إجمالي الأصناف' : 'TOTAL PRODUCTS'}</span><b>1,284</b><span className="muted-cell">{ar ? 'في كل المستودعات' : 'across all warehouses'}</span></div><div className="panel ops-summary-card"><span className="metric-icon amber"><CircleAlert size={17}/></span><span className="eyebrow">{ar ? 'تحتاج إعادة طلب' : 'REORDER NEEDED'}</span><b>07</b><span className="change-down">{ar ? 'أقل من الحد الأدنى' : 'below minimum level'}</span></div><div className="panel ops-summary-card"><span className="metric-icon blue"><Warehouse size={17}/></span><span className="eyebrow">{ar ? 'مستودعات نشطة' : 'ACTIVE WAREHOUSES'}</span><b>04</b><span className="muted-cell">{ar ? 'ضمن ٤ فروع' : 'in 4 branches'}</span></div></div>
  <article className="panel records-panel"><div className="panel-heading"><div><span className="eyebrow">{ar ? 'كتالوج الأصناف' : 'ITEM CATALOG'}</span><h2>{ar ? 'الأصناف في المدار' : 'Items in orbit'}</h2></div><div className="table-actions"><label className="table-search"><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={ar ? 'ابحث بالاسم أو الرمز' : 'Search name or SKU'}/></label><select className="filter-select" value={filter} onChange={(e) => setFilter(e.target.value)} aria-label={ar ? 'تصفية المخزون' : 'Filter inventory'}><option value="all">{ar ? 'كل الأصناف' : 'All items'}</option><option value="available">{ar ? 'متوفر' : 'Available'}</option><option value="low">{ar ? 'منخفض / نافد' : 'Low / out'}</option></select><button className="button button-outline compact"><SlidersHorizontal size={14}/>{ar ? 'خيارات' : 'Options'}</button></div></div><div className="invoice-table-wrap"><table className="data-table inventory-table"><thead><tr><th>{ar ? 'الصنف' : 'Item'}</th><th>SKU</th><th>{ar ? 'التصنيف' : 'Category'}</th><th>{ar ? 'المتوفر' : 'On hand'}</th><th>{ar ? 'الموقع' : 'Location'}</th><th>{ar ? 'السعر' : 'Price'}</th><th>{ar ? 'الحالة' : 'Status'}</th><th/></tr></thead><tbody>{visible.map((p) => <tr key={p.sku}><td><span className="product-cell-icon"><Package size={15}/></span><b>{p.name}</b></td><td><code>{p.sku}</code></td><td className="muted-cell">{p.category}</td><td className={`stock-cell ${p.flag !== 'متوفر' ? 'stock-low' : ''}`}><b>{p.qty}</b><small> {ar ? 'وحدة' : 'units'}</small></td><td className="muted-cell">{p.location}</td><td className="amount-cell">{p.price} <small>ر.س</small></td><td><span className={`status-chip ${p.flag === 'متوفر' ? 'green' : p.flag === 'منخفض' ? 'amber' : 'red'}`}><i/>{p.flag}</span></td><td><button className="icon-button row-arrow" aria-label="open"><ArrowUpLeft size={15}/></button></td></tr>)}</tbody></table></div><div className="table-footer"><span>{ar ? `${visible.length} أصناف معروضة` : `${visible.length} products shown`}</span><div><button className="icon-button" disabled><ArrowDownLeft size={15}/></button><span>1 / 1</span><button className="icon-button" disabled><ArrowUpLeft size={15}/></button></div></div></article>
  <div className="inventory-footnote"><Boxes size={14}/>{ar ? 'الأرصدة والتصنيفات الظاهرة بيانات تجريبية — ابدأ بتوصيل قاعدة البيانات المحلية لإدارة مخزونك.' : 'Stock levels and categories are demo data — connect your local database to manage real inventory.'}</div></section>;
}
